### ISSUE TITLE
BUG: KPI to Death Ratio not populating on refresh

### ISSUE THREAD

**Issue by thezanke** [Clad-Vesto/AlbionSoloScorecard#10]
KPI to Death Ratio doesn't populate properly on refresh but once you click a button it will show the proper value.

![image](https://user-images.githubusercontent.com/3709803/164351030-b89737dd-73b6-4bb2-bfdc-a8e25930cdd6.png)

**Comment by Jusumgi** [comment]
Found the issue in latest commit 5454d5d
ach2deathRatio function was not evaluating properly.
