### ISSUE TITLE
Count sizing

### ISSUE THREAD

**Issue by BenjaminNeilDavis** [Clad-Vesto/AlbionSoloScorecard#17]
Not a major issue but if any of the counts go into double digits the numbers start getting cut off visually.

<img width="337" alt="image" src="https://user-images.githubusercontent.com/6981338/164741798-e7ba649b-69c5-49e8-b5ae-c39c290ad30b.png">

**Comment by Jusumgi** [comment]
On what device/browser are you using? I couldn't reproduce this with Mozilla on either desktop or my cell.

**Comment by BenjaminNeilDavis** [comment]
Ah, I am using Chrome

**Comment by Jusumgi** [comment]
Please check out the new layout, see if it is better for you / if you like it!
